/**
 * Created by liuqing on 2017/5/20.
 */
export const FATCH_ALL_APPGROUP = 'FATCH_ALL_APPGROUP'
export const FATCH_SELF_APPGROUP = 'FATCH_SELF_APPGROUP'
export const ADD_APPGROUP = 'ADD_GROUP'
export const DEL_APPGROUP = 'DEL_APPGROUP'
export const FATCH_APPGROUP_BY_USERNAME = 'FATCH_APPGROUP_BY_USERNAME'
export const FATCH_MARATHON = 'FATCH_MARATHON'
export const MARATHON_CHANGE_LOADING = 'MARATHON_CHANGE_LOADING'
