export const FETCH_DATACENTERS = 'FETCH_DATACENTERS'
export const DATACENTER_ADD = 'DATACENTER_ADD'
export const DATACENTER_UPDATE = 'DATACENTER_UPDATE'
export const DATACENTER_DEL = 'DATACENTER_DEL'
