export const FETCH_FIRST_MENU_RESOURCE = 'FETCH_FIRST_MENU_RESOURCE'
export const FETCH_SECOND_MENU_RESOURCE = 'FETCH_SECOND_MENU_RESOURCE'
export const FETCH_ALL_MENU_RESOURCE = 'FETCH_ALL_MENU_RESOURCE'
export const FETCH_ALL_CHECKED_MENU_RESOURCE = 'FETCH_ALL_CHECKED_MENU_RESOURCE'
