/**
 * Created by liuqing on 2017/5/19.
 */
export const FETCH_TABLE_NODE = 'FETCH_TABLE_NODE'
export const FETCH_ALL_NODE = 'FETCH_ALL_NODE'
export const METRICS_SNAPSHOT = 'METRICS_SNAPSHOT'
export const NODE_INFO = 'NODE_INFO'
export const FETCH_NODE_IMAGES = 'FETCH_NODE_IMAGES'
export const FETCH_NODE_INSTANCES = 'FETCH_NODE_INSTANCES'
export const DEL_NODE_IMAGE = 'DEL_NODE_IMAGE'
export const FETCH_NODE_INSTANCE_INFO = 'FETCH_NODE_INSTANCE_INFO'
