export const DEFAULT_BASE_URL = '/'
// export const DEFAULT_BASE_URL = 'http://172.29.26.21:5013' // uat
// export const DEFAULT_BASE_URL = 'http://172.30.131.25:8090' //  dev
// export const DEFAULT_BASE_URL = 'http://localhost:8080'
export const HASRELOXSTACK = false
export const HASMULTICLUSTER = false
export const HASPROXY = false
export const HASREGISTRY = false
export const SAMPLES_URL = '/static/stack_samples/'
export const DOMAIN = ''
export const AUTH_URL = '/ui/auth'
export const DASH_URL = '/ui'
export const LOGO_ICON = null
export const COMPANY = null
export const DM_VERSION = 'V3.5.0' // 3.5.0 beta2
export const LABEL_PREFIX = 'DM'
